# Uncomment the next line to define a global platform for your project
source 'https://github.com/yoavlt/LiquidFloatingActionButton.git'

platform :ios, '10.0'

  target 'Project' do
    use_frameworks!
    # Add Button
    pod "LiquidFloatingActionButton"
    # Send notification to people in the car
    pod 'PeriscommentView', '0.0.3'

end