# Uncomment the next line to define a global platform for your project
# source 'https://github.com/yoavlt/LiquidFloatingActionButton.git'

platform :ios, '12.0'

  target 'Project' do
    use_frameworks!
    # Add Button
    pod 'LiquidFloatingActionButton', :git => 'https://github.com/alexsanderkhitev/LiquidFloatingActionButton.git'
    # Send notification to people in the car
    pod 'PeriscommentView'
    pod 'SnapKit', '~> 4.2.0'
    pod 'NearbyMessages'
end

post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
        config.build_settings.delete('CODE_SIGNING_ALLOWED')
        config.build_settings.delete('CODE_SIGNING_REQUIRED')
    end
    installer.pods_project.targets.each do |target|
        if ['SideMenuController'].include? target.name
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '3.0'
            end
        end
    end
end
